[project]
name = "ml-npl"
version = "0.1.0"
description = "Team 4 — Sentiment Analysis (NLP). Machine Learning 2026-III, Universidad Distrital Francisco José de Caldas."
authors = [
    {name = "JulianCelisCreator",email = "celisjuliandavid@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kagglehub (>=1.0.2,<2.0.0)",
    "pandas (>=3.0.6,<4.0.0)",
    "pylint (>=4.0.8,<5.0.0)",
]

[tool.poetry]
packages = [{include = "ml_npl"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
